name: markets
description: markets
version: 2.0.0+9

environment:
  sdk: ">=2.2.2 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl_utils: 1.9.0
  cupertino_icons: 1.0.2

  location: 3.0.2
  google_maps_flutter: 1.2.0
  google_map_location_picker: 4.1.6

  fluttertoast: 8.0.1-nullsafety.0
  flutter_staggered_grid_view: 0.4.0-nullsafety.3
  flutter_html: ^1.2.0
  flutter_svg: ^0.19.3

  mvc_pattern: 6.6.4+2
  global_configuration: 2.0.0-nullsafety.0
  html: 0.14.0+4
  url_launcher: 6.0.2
  webview_flutter: 1.0.7
  cached_network_image: 2.5.0
  shared_preferences: 2.0.5
  carousel_slider: 4.0.0-nullsafety.0

  cloud_firestore: 0.14.4
  firebase_auth: 0.18.4+1
  firebase_auth_web: ^0.3.2+1
  firebase_core: 0.5.3
  firebase_messaging: 7.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: 0.17.0
  http: 0.12.2

flutter:
  uses-material-design: true

  assets:
    - assets/cfg/
    - assets/img/
    -
  fonts:
  - family: ProductSans
    fonts:
      - asset: assets/fonts/ProductSans-Thin.ttf
        weight: 100
      - asset: assets/fonts/ProductSans-Thin.ttf
        weight: 200
      - asset: assets/fonts/ProductSans-Light.ttf
        weight: 300
      - asset: assets/fonts/ProductSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/ProductSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/ProductSans-Bold.ttf
        weight: 600
      - asset: assets/fonts/ProductSans-Black.ttf
        weight: 700
      - asset: assets/fonts/ProductSans-Black.ttf
        weight: 800
      - asset: assets/fonts/ProductSans-Black.ttf
        weight: 900

flutter_intl:
  enabled: true
